[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'lib/EnsPrimaryContractNamer/']


optimizer = true
optimizer_runs = 2_000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[profile.etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
